#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

file="$1"
decoded=""

while read -r line; do
    first_letter=$(echo "$line" | awk '{print $1}' | cut -c 1)
    decoded="$decoded$first_letter"
done < "$file"

echo "$decodeed"
